import type { ProspectingProvider, ProspectRecord } from "./types";

const lastUpdated = new Date().toISOString();

export const manualProspects: ProspectRecord[] = [
  {
    id: "manual-verdun-longue-detention",
    address: "4821 rue Wellington",
    city: "Montréal",
    propertyType: "Duplex",
    category: "Vendeurs potentiels",
    reason: "Propriété détenue depuis plus de 18 ans dans un secteur où les ventes récentes indiquent une forte demande pour les plex bien situés.",
    opportunityScore: 91,
    priority: "Élevée",
    source: "manual",
    url: null,
    lastUpdated,
    notes: "Longue détention, secteur recherché, potentiel de repositionnement locatif.",
  },
  {
    id: "manual-laval-succession",
    address: "2145 boulevard des Laurentides",
    city: "Laval",
    propertyType: "Maison",
    category: "Successions",
    reason: "Signal simulé de transfert successoral et propriété unifamiliale dans un secteur où les maisons détachées se vendent rapidement lorsqu'elles sont bien préparées.",
    opportunityScore: 88,
    priority: "Élevée",
    source: "manual",
    url: null,
    lastUpdated,
    notes: "Succession probable, demande familiale, préparation de mise en marché utile.",
  },
  {
    id: "manual-longueuil-expiree",
    address: "739 rue Saint-Charles Ouest",
    city: "Longueuil",
    propertyType: "Condo",
    category: "Propriétés expirées",
    reason: "Inscription simulée expirée après une période prolongée sur le marché. Opportunité de repositionnement du prix, des visuels et du message.",
    opportunityScore: 84,
    priority: "Élevée",
    source: "manual",
    url: null,
    lastUpdated,
    notes: "Annonce expirée, temps sur marché élevé, nouvelle stratégie requise.",
  },
  {
    id: "manual-terrebonne-equite",
    address: "1180 croissant des Fougères",
    city: "Terrebonne",
    propertyType: "Maison",
    category: "Propriétés à forte équité",
    reason: "Achat simulé de longue date avec appréciation importante du secteur. Le propriétaire pourrait avoir une forte équité mobilisable.",
    opportunityScore: 79,
    priority: "Moyenne",
    source: "manual",
    url: null,
    lastUpdated,
    notes: "Équité probable élevée, quartier familial, marché de maisons actif.",
  },
  {
    id: "manual-quebec-multiplex",
    address: "905 3e Avenue",
    city: "Québec",
    propertyType: "Triplex",
    category: "Multiplex",
    reason: "Triplex dans un secteur locatif stable avec potentiel d'optimisation. Les investisseurs recherchent des immeubles avec revenus prévisibles.",
    opportunityScore: 82,
    priority: "Élevée",
    source: "manual",
    url: null,
    lastUpdated,
    notes: "Immeuble à revenus, secteur locatif, demande investisseurs.",
  },
  {
    id: "manual-sherbrooke-terrain",
    address: "Chemin Sainte-Catherine",
    city: "Sherbrooke",
    propertyType: "Terrain",
    category: "Terrains",
    reason: "Terrain simulé près d'un axe de développement local. Potentiel à vérifier selon zonage, services et usages permis.",
    opportunityScore: 73,
    priority: "Moyenne",
    source: "manual",
    url: null,
    lastUpdated,
    notes: "Terrain vacant, zonage à valider, potentiel promoteur.",
  },
  {
    id: "manual-gatineau-finance",
    address: "66 rue de la Falaise",
    city: "Gatineau",
    propertyType: "Maison",
    category: "Reprises de finance",
    reason: "Signal fictif de difficulté financière et propriété dans un secteur où une vente encadrée pourrait réduire les risques pour le propriétaire.",
    opportunityScore: 76,
    priority: "Moyenne",
    source: "manual",
    url: null,
    lastUpdated,
    notes: "Risque financier simulé, intervention rapide utile, approche délicate requise.",
  },
  {
    id: "manual-brossard-investisseur",
    address: "3105 avenue Panama",
    city: "Brossard",
    propertyType: "Commercial",
    category: "Opportunités investisseurs",
    reason: "Emplacement simulé près d'un pôle de transport et d'activités commerciales. Potentiel d'intérêt pour acheteurs investisseurs.",
    opportunityScore: 80,
    priority: "Élevée",
    source: "manual",
    url: null,
    lastUpdated,
    notes: "Localisation stratégique, profil investisseur, potentiel de repositionnement.",
  },
];

export const manualProvider: ProspectingProvider = {
  id: "manual",
  label: "Liste manuelle",
  enabled: true,
  getProspects: () => manualProspects,
};
