"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useDashboardAuth } from "@/components/auth/DashboardAuthProvider";
import { relationshipLabels, relationshipTypes, type RelatedContact, type RelationshipType, type RelationshipView } from "@/lib/client-relationships";

export function ClientRelationships({clientId,cases=[]}:{clientId:string;cases?:{id:string;title?:string}[]}) {
 const {authenticatedFetch,status}=useDashboardAuth();
 const [relations,setRelations]=useState<RelationshipView[]>([]),[query,setQuery]=useState(""),[matches,setMatches]=useState<RelatedContact[]>([]),[selected,setSelected]=useState(""),[type,setType]=useState<RelationshipType>("spouse"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[linking,setLinking]=useState(false),[caseId,setCaseId]=useState("");
 const load=useCallback(async()=>{if(status!=="authenticated")return;setLoading(true);try{const r=await authenticatedFetch(`/api/clients/${clientId}/relationships`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setRelations(b.relationships);setError("");}catch(e){setError(e instanceof Error?e.message:"Relations indisponibles.");}finally{setLoading(false);}},[authenticatedFetch,status,clientId]);
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("crm-updated",refresh);return()=>window.removeEventListener("crm-updated",refresh);},[load]);
 useEffect(()=>{let active=true;setSelected("");setMatches([]);if(!linking||query.trim().length<2)return;const timer=setTimeout(async()=>{try{const r=await authenticatedFetch(`/api/clients?q=${encodeURIComponent(query.trim())}`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);if(active)setMatches((b.clients||[]).filter((c:RelatedContact)=>c.id!==clientId));}catch(e){if(active)setError(e instanceof Error?e.message:"Recherche indisponible.");}},250);return()=>{active=false;clearTimeout(timer);};},[query,linking,authenticatedFetch,clientId]);
 async function save(body:Record<string,string>){setBusy(true);setError("");setNotice("");try{const r=await authenticatedFetch(`/api/clients/${clientId}/relationships`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error);setNotice(body.action==="add_to_case"?(b.added?"Participant ajouté à ce dossier seulement.":"Ce contact participe déjà à ce dossier."):"Relation enregistrée des deux côtés. Les fiches restent distinctes.");setLinking(false);setQuery("");window.dispatchEvent(new Event("crm-updated"));await load();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setBusy(false);}}
 return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Liens / Relations</h2><button type="button" disabled={busy} onClick={()=>setLinking(!linking)} className="min-h-11 rounded-xl border px-4 text-sm">{linking?"Fermer":"Relier un contact"}</button></div>
 <p className="mt-2 text-sm text-slate-500">Chaque personne garde sa fiche et son adresse. Les participants des dossiers se choisissent séparément.</p>
 {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}{notice?<p role="status" className="mt-3 text-sm text-teal-700">{notice}</p>:null}
 {loading?<p className="mt-3 text-sm">Chargement des relations…</p>:!relations.length&&!error?<p className="mt-3 text-sm text-slate-500">Aucun contact relié.</p>:null}
 <div className="mt-4 space-y-3">{relations.map(r=><div key={r.id} className="rounded-xl border border-slate-200 p-4"><p className="text-sm">{r.type==="spouse"?"❤️ ":""}{r.label}</p><Link href={`/tableau-de-bord/clients/${r.contact.id}`} className="font-semibold text-teal-700 underline">{r.contact.first_name} {r.contact.last_name}</Link><Link href={`/tableau-de-bord/clients/${r.contact.id}`} className="ml-3 text-sm underline">Ouvrir la fiche</Link>{cases.length?<div className="mt-3 flex flex-wrap gap-2"><label className="text-sm">Dossier à partager<select aria-label={`Dossier pour ${r.contact.first_name}`} value={caseId} onChange={e=>setCaseId(e.target.value)} className="ml-2 rounded-lg border bg-transparent p-2"><option value="">Choisir un dossier</option>{cases.map(c=><option key={c.id} value={c.id}>{c.title||"Dossier"}</option>)}</select></label><button disabled={busy||!caseId} type="button" className="min-h-11 rounded-lg border px-3 text-sm disabled:opacity-50" onClick={()=>void save({action:"add_to_case",relatedClientId:r.contact.id,caseId})}>Ajouter comme participant</button></div>:null}</div>)}</div>
 {linking?<form className="mt-4 space-y-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-950" onSubmit={e=>{e.preventDefault();void save({relatedClientId:selected,type});}}><label className="block text-sm">Chercher un contact existant<input value={query} onChange={e=>setQuery(e.target.value)} className="mt-1 w-full rounded-lg border bg-transparent p-3 text-base" placeholder="Prénom ou nom" /></label><div className="max-h-60 space-y-2 overflow-auto">{matches.map(c=><label key={c.id} className="flex gap-2 rounded-lg border p-3 text-sm"><input type="radio" name="related-contact" value={c.id} checked={selected===c.id} onChange={()=>setSelected(c.id)} />{c.first_name} {c.last_name}{c.email?` · ${c.email}`:""}</label>)}</div><label className="block text-sm">Cette personne est le/la… du contact choisi<select value={type} onChange={e=>setType(e.target.value as RelationshipType)} className="ml-2 rounded-lg border bg-transparent p-2">{relationshipTypes.map(t=><option key={t} value={t}>{relationshipLabels[t]}</option>)}</select></label><button type="submit" disabled={!selected||busy} className="min-h-11 rounded-xl bg-teal-700 px-4 text-white disabled:opacity-50">Enregistrer la relation</button></form>:null}</section>;
}
