"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, FileText, Loader2, Save, UserRound } from "lucide-react";

import { SessionStatusNotice, useDashboardAuth } from "@/components/auth/DashboardAuthProvider";

type Payload = { property: Record<string, any>; relations: Array<Record<string, any>>; cases: Array<Record<string, any>>; documents: Array<Record<string, any>> };

export function PropertyWorkspace({ propertyId, returnHref, returnLabel }: { propertyId: string; returnHref?: string; returnLabel?: string }) {
  const { status, authenticatedFetch } = useDashboardAuth();
  const [data, setData] = useState<Payload | null>(null);
  const [form, setForm] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const load = useCallback(async () => {
    if (status !== "authenticated") return;
    setLoading(true);
    try { const response = await authenticatedFetch(`/api/properties/${propertyId}`, { cache: "no-store" }); const payload = await response.json() as Payload & { error?: string }; if (!response.ok) throw new Error(payload.error || "Chargement impossible."); setData(payload); setForm({ address: payload.property.address || "", city: payload.property.city || "", postalCode: payload.property.postal_code || "", propertyType: payload.property.property_type || "", lotNumber: payload.property.lot_number || "" }); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Chargement impossible."); } finally { setLoading(false); }
  }, [authenticatedFetch, propertyId, status]);
  useEffect(() => { void load(); }, [load]);
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await authenticatedFetch(`/api/properties/${propertyId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ values: form }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error || "Enregistrement impossible."); setNotice("La propriété est enregistrée dans la fiche centrale."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Enregistrement impossible."); } finally { setSaving(false); } }
  if (loading || !data) return <div className="flex min-h-96 items-center justify-center">{error ? <p className="text-red-700">{error}</p> : <Loader2 className="h-8 w-8 animate-spin text-teal-700" />}</div>;
  const back = safeBack(returnHref) || (data.cases[0] ? `/tableau-de-bord/dossiers/${data.cases[0].id}` : "/tableau-de-bord/clients");
  return <div className="space-y-6"><nav className="text-sm"><Link href={back} className="inline-flex items-center gap-2 font-semibold text-teal-700"><ArrowLeft className="h-4 w-4" />Retour {returnLabel ? `à ${returnLabel}` : "au dossier"}</Link></nav><header className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-sm font-semibold text-teal-300">Fiche propriété</p><h1 className="mt-2 text-3xl font-semibold">{data.property.address || "Adresse à confirmer"}</h1><p className="mt-2 text-slate-300">{[data.property.city, data.property.postal_code, data.property.property_type].filter(Boolean).join(" · ")}</p></header><SessionStatusNotice />{error ? <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}{notice ? <p className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p> : null}
    <section id="modifier" className="scroll-mt-6 rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-semibold">Modifier la propriété</h2><form onSubmit={save} className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Adresse" value={form.address} onChange={(value) => setForm({ ...form, address: value })} wide /><Field label="Ville" value={form.city} onChange={(value) => setForm({ ...form, city: value })} /><Field label="Code postal" value={form.postalCode} onChange={(value) => setForm({ ...form, postalCode: value })} /><Field label="Type de propriété" value={form.propertyType} onChange={(value) => setForm({ ...form, propertyType: value })} /><Field label="Numéro de lot" value={form.lotNumber} onChange={(value) => setForm({ ...form, lotNumber: value })} /><button type="submit" disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-teal-700 px-4 font-semibold text-white sm:col-span-2">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Enregistrer</button></form></section>
    <div className="grid gap-6 xl:grid-cols-2"><Section title="Clients reliés">{data.relations.map((item, index) => { const client = Array.isArray(item.client) ? item.client[0] : item.client; return client ? <Link key={client.id || index} href={`/tableau-de-bord/clients/${client.id}?from=${encodeURIComponent(`/tableau-de-bord/proprietes/${propertyId}`)}&fromLabel=propriété`} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-800"><UserRound className="h-5 w-5 text-teal-700" /><span><strong className="block">{`${client.first_name || ""} ${client.last_name || ""}`.trim()}</strong><span className="text-xs text-slate-500">{client.email || client.phone || "Coordonnées à compléter"}</span></span></Link> : null; })}</Section><Section title="Dossiers et pipeline">{data.cases.map((item) => <Link key={item.id} href={`/tableau-de-bord/dossiers/${item.id}`} className="block rounded-xl border border-slate-200 p-3 dark:border-slate-800"><strong>{item.title}</strong><p className="text-xs text-slate-500">{item.case_type} · {item.current_stage || item.pipeline_stage}</p></Link>)}</Section><Section title="Documents">{data.documents.map((item) => <div key={item.id} className="flex gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-800"><FileText className="h-5 w-5 text-teal-700" /><span><strong className="block text-sm">{item.name}</strong><span className="text-xs text-slate-500">{item.category}</span></span></div>)}</Section></div>
  </div>;
}
function Field({ label, value, onChange, wide = false }: { label: string; value: string; onChange: (value: string) => void; wide?: boolean }) { return <label className={`text-sm font-semibold ${wide ? "sm:col-span-2" : ""}`}>{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 font-normal dark:border-slate-700 dark:bg-slate-950" /></label>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { const hasItems = Array.isArray(children) ? children.some(Boolean) : Boolean(children); return <section className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-4 space-y-3">{hasItems ? children : <p className="text-sm text-slate-500">Aucun élément relié.</p>}</div></section>; }
function safeBack(value?: string) { return value?.startsWith("/tableau-de-bord/") && !value.startsWith("//") ? value : ""; }
