"use client";

import { useState } from "react";
import Link from "next/link";
import { Camera, CheckCircle2, FileUp, Keyboard, Loader2, Mic, MoreHorizontal, Phone, Plus, Sparkles, X } from "lucide-react";

import { useDashboardAuth } from "@/components/auth/DashboardAuthProvider";
import { VoiceDictationButton } from "@/components/voice-dictation-button";

type AnalysisPayload = { captureId: string; analysis: any; engine: string; potentialDuplicates: Array<any>; suggestedClientId: string | null; requiresChoice: boolean };
const choices = [
  { type: "voice", label: "Parler", icon: Mic }, { type: "text", label: "Écrire", icon: Keyboard },
  { type: "image", label: "Photo / capture", icon: Camera, href: "/tableau-de-bord/importer?source=image" },
  { type: "document", label: "Document", icon: FileUp, href: "/tableau-de-bord/importer?source=document" },
  { type: "call", label: "Appel", icon: Phone, href: "/tableau-de-bord/appels" }, { type: "other", label: "Autre", icon: MoreHorizontal },
];

export function UniversalQuickCapture({ floating = false }: { floating?: boolean }) {
  const { authenticatedFetch } = useDashboardAuth();
  const [open, setOpen] = useState(false);
  const [sourceType, setSourceType] = useState("text");
  const [text, setText] = useState("");
  const [analysis, setAnalysis] = useState<AnalysisPayload | null>(null);
  const [clientId, setClientId] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [created, setCreated] = useState<{ caseId: string; taskCount: number } | null>(null);

  function begin(type: string) { setSourceType(type); setOpen(true); setAnalysis(null); setCreated(null); setError(""); }
  async function analyze() { setBusy(true); setError(""); try { const response = await authenticatedFetch("/api/crm/inbox/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text, sourceType }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Analyse impossible."); setAnalysis(payload); setClientId(payload.suggestedClientId || null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Analyse impossible."); } finally { setBusy(false); } }
  async function confirm() { if (!analysis) return; if (analysis.potentialDuplicates.length && !clientId) { setError("Choisis la fiche existante à relier. IACourtier ne créera pas de doublon sans confirmation."); return; } setBusy(true); setError(""); try { const response = await authenticatedFetch("/api/crm/inbox/confirm", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ captureId: analysis.captureId, clientId }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Confirmation impossible."); setCreated({ caseId: payload.caseId, taskCount: payload.taskCount || 0 }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Confirmation impossible."); } finally { setBusy(false); } }

  return <>
    {floating ? <button type="button" onClick={() => begin("text")} className="fixed bottom-5 right-5 z-50 inline-flex h-14 w-14 items-center justify-center rounded-full bg-teal-700 text-white shadow-2xl ring-4 ring-white/80 hover:bg-teal-800 dark:ring-slate-950/80" aria-label="Capture rapide"><Plus className="h-7 w-7" /></button> : <section className="rounded-3xl border border-teal-200 bg-gradient-to-br from-teal-50 to-white p-5 shadow-sm dark:border-teal-900 dark:from-teal-950/30 dark:to-slate-900 sm:p-7"><p className="inline-flex items-center gap-2 text-sm font-semibold text-teal-700"><Sparkles className="h-5 w-5" />Boîte d’entrée IA</p><h2 className="mt-2 text-2xl font-semibold">J’ai quelque chose à faire</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Décris-le une fois. IACourtier identifie la personne, vérifie les doublons et prépare le dossier et les actions avant ta confirmation.</p><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{choices.map((choice) => choice.href ? <Link key={choice.type} href={choice.href} className="flex min-h-24 flex-col justify-between rounded-2xl border border-teal-200 bg-white p-3 text-sm font-semibold hover:border-teal-500 dark:border-teal-900 dark:bg-slate-950"><choice.icon className="h-5 w-5 text-teal-700" />{choice.label}</Link> : <button key={choice.type} type="button" onClick={() => begin(choice.type)} className="flex min-h-24 flex-col justify-between rounded-2xl border border-teal-200 bg-white p-3 text-left text-sm font-semibold hover:border-teal-500 dark:border-teal-900 dark:bg-slate-950"><choice.icon className="h-5 w-5 text-teal-700" />{choice.label}</button>)}</div></section>}
    {open ? <div className="fixed inset-0 z-[70] flex items-end justify-center bg-slate-950/60 sm:items-center sm:p-4" role="dialog" aria-modal="true"><div className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl dark:bg-slate-900 sm:rounded-3xl sm:p-7"><header className="flex items-start justify-between"><div><p className="text-sm font-semibold text-teal-700">Capture rapide universelle</p><h2 className="mt-1 text-2xl font-semibold">{created ? "C’est classé" : analysis ? "Voici ce que j’ai compris" : "Qu’est-ce qu’il faut faire?"}</h2></div><button type="button" onClick={() => setOpen(false)} aria-label="Fermer" className="rounded-full border border-slate-200 p-2 dark:border-slate-700"><X className="h-5 w-5" /></button></header>{created ? <div className="mt-8 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600" /><p className="mt-4 font-semibold">Le dossier central et {created.taskCount} action{created.taskCount > 1 ? "s" : ""} sont enregistrés.</p><Link href={`/tableau-de-bord/dossiers/${created.caseId}`} className="mt-6 inline-flex min-h-12 items-center rounded-xl bg-teal-700 px-5 font-semibold text-white">Ouvrir le dossier</Link></div> : analysis ? <Preview payload={analysis} clientId={clientId} setClientId={setClientId} /> : <div className="mt-6"><textarea value={text} onChange={(event) => setText(event.target.value)} rows={7} autoFocus className="w-full rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-950" placeholder="Ex. Jean est vendeur d’un duplex à Lavaltrie. Il faut l’appeler demain matin et vérifier son certificat de localisation." />{sourceType === "voice" ? <VoiceDictationButton className="mt-3" onTranscript={(value) => setText((current) => [current, value].filter(Boolean).join(" "))} label="Commencer la dictée" /> : null}</div>}{error ? <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}{!created ? <button type="button" onClick={() => void (analysis ? confirm() : analyze())} disabled={busy || (!analysis && !text.trim())} className="mt-6 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-teal-700 px-5 font-semibold text-white disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}{analysis ? "Confirmer et créer / mettre à jour le dossier" : "Analyser avant de créer"}</button> : null}</div></div> : null}
  </>;
}

function Preview({ payload, clientId, setClientId }: { payload: AnalysisPayload; clientId: string | null; setClientId: (value: string | null) => void }) { const item = payload.analysis; const name = `${item.person.firstName || ""} ${item.person.lastName || ""}`.trim() || "À identifier"; return <div className="mt-6 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Datum label="Personne détectée" value={name} /><Datum label="Dossier suggéré" value={label(item.caseType)} /><Datum label="Demande" value={item.request} /><Datum label="Urgence" value={label(item.urgency)} /></div>{item.property?.address || item.property?.city ? <Datum label="Propriété / secteur" value={[item.property.address, item.property.city, item.property.propertyType].filter(Boolean).join(" · ")} /> : null}<div><h3 className="text-sm font-semibold">Actions préparées</h3><div className="mt-2 space-y-2">{item.tasks.map((task: any, index: number) => <div key={`${task.title}-${index}`} className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-950"><strong>{task.title}</strong><span className="mt-1 block text-xs text-slate-500">{label(task.actionType)}{task.dueAt ? ` · ${new Intl.DateTimeFormat("fr-CA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(task.dueAt))}` : " · date à planifier"}</span></div>)}</div></div>{payload.potentialDuplicates.length ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-900 dark:bg-amber-950/20"><h3 className="font-semibold text-amber-950 dark:text-amber-100">Fiches existantes possibles</h3><p className="mt-1 text-xs text-amber-800 dark:text-amber-200">Choisis la bonne personne. Aucun doublon ne sera créé automatiquement.</p><div className="mt-3 space-y-2">{payload.potentialDuplicates.map((client) => <label key={client.id} className="flex cursor-pointer items-start gap-3 rounded-xl bg-white p-3 text-sm dark:bg-slate-950"><input type="radio" name="client-match" checked={clientId === client.id} onChange={() => setClientId(client.id)} /><span><strong>{`${client.first_name || ""} ${client.last_name || ""}`.trim()}</strong><span className="block text-xs text-slate-500">{[client.phone, client.email, client.reasons?.join(", ")].filter(Boolean).join(" · ")}</span></span></label>)}</div></div> : <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">Aucune fiche existante certaine : une seule fiche sera créée après confirmation.</p>}{item.missingInformation?.length ? <div><h3 className="text-sm font-semibold">Renseignements manquants</h3><p className="mt-1 text-sm text-slate-500">{item.missingInformation.join(" · ")}</p></div> : null}</div>; }
function Datum({ label: title, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 p-3 dark:border-slate-800"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-1 text-sm">{value || "À confirmer"}</p></div>; }
function label(value?: string) { return String(value || "").replace(/_/g, " ").replace(/^./, (letter) => letter.toUpperCase()); }

